In [8]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [10]:
df=pd.read_csv("students_data.csv")
df

     StudyHours  Attendance  Assignments  PreviousMarks Result
0           7.5          92           95             88   Pass
1           3.2          61           55             45   Fail
2           6.8          85           88             78   Pass
3           2.1          45           40             32   Fail
4           8.2          96           98             92   Pass
..          ...         ...          ...            ...    ...
96          3.8          60           54             47   Fail
97          6.4          84           84             76   Pass
98          8.2          95           96             91   Pass
99          2.5          50           43             34   Fail
100         6.0          80           78             71   Pass

[101 rows x 5 columns]

In [11]:
x=df.drop(columns=['Result'])
x

     StudyHours  Attendance  Assignments  PreviousMarks
0           7.5          92           95             88
1           3.2          61           55             45
2           6.8          85           88             78
3           2.1          45           40             32
4           8.2          96           98             92
..          ...         ...          ...            ...
96          3.8          60           54             47
97          6.4          84           84             76
98          8.2          95           96             91
99          2.5          50           43             34
100         6.0          80           78             71

[101 rows x 4 columns]

In [13]:
y=df['Result']
y

0      Pass
1      Fail
2      Pass
3      Fail
4      Pass
       ...
96     Fail
97     Pass
98     Pass
99     Fail
100    Pass
Name: Result, Length: 101, dtype: object

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
DecisionTreeClassifier()

DecisionTreeClassifier()

In [24]:
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [29]:
predictions=model.predict(X_test)

In [32]:
score=accuracy_score(Y_test,predictions)
score

0.9523809523809523

In [34]:
import pandas as pd

new_student = pd.DataFrame({
    'StudyHours': [5],
    'Attendance': [88],
    'Assignments': [8],
    'PreviousMarks': [72]
})

model.predict(new_student)

array(['Pass'], dtype=object)

In [35]:
score=accuracy_score(Y_test,predictions)
score

0.9523809523809523